---
- name: Copying Kubernetes repo file
  become: true
  tags: kube

  copy:
   src: ./files/kubernetes.repo
   dest: /etc/yum.repos.d/kubernetes.repo
- name: Installing Kubeadm Kubelet Kubectl 
  become: true
  tags: kube
  yum:
   state: present
   name: 
    - kubeadm
    - kubelet
    - kubectl
...
