---
# tasks file for application

 - name: Checkout The Code From Github Using Ansible.
   git:
     repo: https://github.com/beselvan/LoginApp.git
     dest: /home/mycloud245/LoginApp
   tags: checkout

 - shell: mvn -f /home/mycloud245/LoginApp/pom.xml package
   register: mavenlog
   tags: maven

 - debug:
    var: mavenlog
   tags: maven

 - name: Docker-Compose the package
   become: true
   shell: docker-compose -f /home/mycloud245/LoginApp/docker-compose.yml  up -d
   register: log
   tags: docker

 - name: Docker-Compose the package
   debug:
    var: log
   tags: docker
