---
#- name: Jenkins Repo download
#  get_url:
#   url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
#   dest: /etc/yum.repos.d/jenkins.repo
#
#- name: Jenkins Key Importing
#  rpm_key:
#    state: present
#    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key


- name: Jenkins Repo download
  copy:
   src: ./files/jenkins.repo
   dest: /etc/yum.repos.d/jenkins.repo

- name: Jenkins Key download
  copy:
   src: ./files/jenkins-ci.org.key
   dest: /etc/yum.repos.d/

- name: Jenkins Key Importing
  become: true
  shell: "rpm --import /etc/yum.repos.d/jenkins-ci.org.key"

- name: Jenkins Installation
  yum:
   name: jenkins
   state: present

- name: Jenkins job creation
  copy:
   src: ./files/LoginApp
   dest: /var/lib/jenkins/jobs/
   owner: jenkins
  tags: copy

- name: Adding jenkins user to docker
  user:
    name: jenkins
    group: docker

- name: Jenkins Service Start & Enable 
  become: true
  service:
   name: jenkins
   state: started
   enabled: true
  tags: restart

#- name: Get init password Jenkins
#  become: true
#  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
#  register: result
#- name: Print password
#  debug:
#   var: result.stdout
...
